### ISSUE TITLE
Capacity test using bbbot

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#212]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1500, http://dev.mconf.org/redmine/issues/1500
Original Date: 2015-05-18
Original Assignee: Pedro Beschorner Marin

---

Test if bbbot is working properly with the latest code.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2015-03-30T19:58:44Z

---

Running: java -jar bin/bbbot.jar --server MY_SERVER --key MY_SALT --numbots 50 --meeting "70d46f92-9b25-4827-84d7-9fcfadf34460-1397514301" --single_meeting --interval 2000

The number of bots connected to listen only varies (46~50). This seem to happen in some kind of random way. Still couldn't isolate the problem and couldn't reproduce with less than 20 bots.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2015-04-02T15:32:17Z

---

Two way audio seems OK.

Running: 

-jar bin/bbbot.jar --server http://10.0.3.100 --key c40fb828a670251f5bcb79b462e1333c --numbots 50 --meeting "70d46f92-9b25-4827-84d7-9fcfadf34460-1397514301" --single_meeting --interval 1000 --audio "etc/audio-sample.flv" --two_way_audio

and

-jar bin/bbbot.jar --server http://10.0.3.100 --key c40fb828a670251f5bcb79b462e1333c --numbots 50 --meeting "70d46f92-9b25-4827-84d7-9fcfadf34460-1397514301" --single_meeting --interval 1000 --audio "etc/audio-sample.flv" --two_way_audio --everyone_sends_audio true --only_one_sends_audio false

Although some bots are not disconnecting correctly.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2015-04-02T18:31:30Z

---

Found something related with the listen only issue.

https://github.com/pedrobmarin/bigbluebutton/blob/master/bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala#L36

users.getUserWithExternalId(msg.userid) is returning None so outGW.send(new UserListeningOnly(meetingID, recorded, uvo.userID, uvo.listenOnly)) never happens for this user.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2015-04-06T19:36:24Z

---

Fixed the listen only issue.

Working on an flazr exception thrown when bots are disconnecting:

16:22:10,252 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - exception: [id: 0x75a287d9, /10.0.3.1:39533 => /10.0.3.100:1935] EXCEPTION: java.nio.channels.ClosedChannelException
16:22:10,254 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - cause: java.nio.channels.ClosedChannelException
16:22:10,254 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - message: null
16:22:10,254 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - stacktrace: java.nio.channels.ClosedChannelException
    at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
    at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:240)
    at org.jboss.netty.channel.socket.nio.NioWorker.write0(NioWorker.java:472)
    at org.jboss.netty.channel.socket.nio.NioWorker.writeFromTaskLoop(NioWorker.java:395)
    at org.jboss.netty.channel.socket.nio.NioSocketChannel$WriteTask.run(NioSocketChannel.java:268)
    at org.jboss.netty.channel.socket.nio.NioWorker.processWriteTaskQueue(NioWorker.java:270)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

16:22:10,256 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - exception: [id: 0x75a287d9, /10.0.3.1:39533 :> /10.0.3.100:1935] EXCEPTION: java.nio.channels.ClosedChannelException
16:22:10,256 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - cause: java.nio.channels.ClosedChannelException
16:22:10,256 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - message: null
16:22:10,256 [New I/O client worker #22-1] WARN [com.flazr.util.ChannelUtils] - stacktrace: java.nio.channels.ClosedChannelException
    at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
    at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:240)
    at org.jboss.netty.channel.socket.nio.NioWorker.write0(NioWorker.java:472)
    at org.jboss.netty.channel.socket.nio.NioWorker.writeFromTaskLoop(NioWorker.java:395)
    at org.jboss.netty.channel.socket.nio.NioSocketChannel$WriteTask.run(NioSocketChannel.java:268)
    at org.jboss.netty.channel.socket.nio.NioWorker.processWriteTaskQueue(NioWorker.java:270)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
